
[upgrades]
	#The additional energy used by the Range Upgrade
	#Range: > 0
	rangeUpgradeUsage = 128
	#The additional energy used by the Speed Upgrade
	#Range: > 0
	speedUpgradeUsage = 8
	#The additional energy used by the Crafting Upgrade
	#Range: > 0
	craftingUpgradeUsage = 64
	#The additional energy used by the Stack Upgrade
	#Range: > 0
	stackUpgradeUsage = 32
	#The additional energy used by the Silk Touch Upgrade
	#Range: > 0
	silkTouchUpgradeUsage = 512
	#The additional energy used by the Fortune 1 Upgrade
	#Range: > 0
	fortune1UpgradeUsage = 64
	#The additional energy used by the Fortune 2 Upgrade
	#Range: > 0
	fortune2UpgradeUsage = 128
	#The additional energy used by the Fortune 3 Upgrade
	#Range: > 0
	fortune3UpgradeUsage = 256
	#The additional energy used by the Regulator Upgrade
	#Range: > 0
	regulatorUpgradeUsage = 64

[controller]
	#The energy capacity of the Controller
	#Range: > 0
	capacity = 10000000
	#The base energy used by the Controller
	#Range: > 0
	baseUsage = 256

[cable]
	#The energy used by the Cable
	#Range: > 0
	usage = 5

[grid]
	#The energy used by Grids
	#Range: > 0
	gridUsage = 64
	#The energy used by Crafting Grids
	#Range: > 0
	craftingGridUsage = 128
	#The energy used by Pattern Grids
	#Range: > 0
	patternGridUsage = 128
	#The energy used by Fluid Grids
	#Range: > 0
	fluidGridUsage = 64

[diskDrive]
	#The energy used by the Disk Drive
	#Range: > 0
	usage = 512
	#The energy used per disk in the Disk Drive
	#Range: > 0
	diskUsage = 512

[storageBlock]
	#The energy used by the 1k Storage Block
	#Range: > 0
	oneKUsage = 8
	#The energy used by the 4k Storage Block
	#Range: > 0
	fourKUsage = 24
	#The energy used by the 16k Storage Block
	#Range: > 0
	sixteenKUsage = 72
	#The energy used by the 64k Storage Block
	#Range: > 0
	sixtyFourKUsage = 216

[fluidStorageBlock]
	#The energy used by the 64k Fluid Storage Block
	#Range: > 0
	sixtyFourKUsage = 8
	#The energy used by the 256k Fluid Storage Block
	#Range: > 0
	twoHundredFiftySixKUsage = 24
	#The energy used by the 1024k Fluid Storage Block
	#Range: > 0
	thousandTwentyFourKUsage = 72
	#The energy used by the 4096k Fluid Storage Block
	#Range: > 0
	fourThousandNinetySixKUsage = 216

[externalStorage]
	#The energy used by the External Storage
	#Range: > 0
	usage = 32

[importer]
	#The energy used by the Importer
	#Range: > 0
	usage = 16

[exporter]
	#The energy used by the Exporter
	#Range: > 0
	usage = 16

[networkReceiver]
	#The energy used by the Network Receiver
	#Range: > 0
	usage = 16

[networkTransmitter]
	#The energy used by the Network Transmitter
	#Range: > 0
	usage = 512

[relay]
	#The energy used by the Relay
	#Range: > 0
	usage = 16

[detector]
	#The energy used by the Detector
	#Range: > 0
	usage = 16

[securityManager]
	#The energy used by the Security Manager
	#Range: > 0
	usage = 32
	#The additional energy used by Security Cards in the Security Manager
	#Range: > 0
	usagePerCard = 16

[interface]
	#The energy used by the Interface
	#Range: > 0
	usage = 32

[fluidInterface]
	#The energy used by the Fluid Interface
	#Range: > 0
	usage = 32

[wirelessTransmitter]
	#The energy used by the Wireless Transmitter
	#Range: > 0
	usage = 512
	#The base range of the Wireless Transmitter
	#Range: > 0
	baseRange = 64
	#The additional range per Range Upgrade in the Wireless Transmitter
	#Range: > 0
	rangePerUpgrade = 64

[storageMonitor]
	#The energy used by the Storage Monitor
	#Range: > 0
	usage = 16

[wirelessGrid]
	#The energy capacity of the Wireless Grid
	#Range: > 0
	capacity = 640000
	#The energy used by the Wireless Grid to open
	#Range: > 0
	openUsage = 1500
	#The energy used by the Wireless Grid to extract items
	#Range: > 0
	extractUsage = 100
	#The energy used by the Wireless Grid to insert items
	#Range: > 0
	insertUsage = 100

[wirelessFluidGrid]
	#The energy capacity of the Wireless Fluid Grid
	#Range: > 0
	capacity = 640000
	#The energy used by the Wireless Fluid Grid to open
	#Range: > 0
	openUsage = 1500
	#The energy used by the Wireless Fluid Grid to extract fluids
	#Range: > 0
	extractUsage = 100
	#The energy used by the Wireless Fluid Grid to insert fluids
	#Range: > 0
	insertUsage = 100

[constructor]
	#The energy used by the Constructor
	#Range: > 0
	usage = 128

[destructor]
	#The energy used by the Destructor
	#Range: > 0
	usage = 128

[diskManipulator]
	#The energy used by the Disk Manipulator
	#Range: > 0
	usage = 512

[portableGrid]
	#The energy capacity of the Portable Grid
	#Range: > 0
	capacity = 640000
	#The energy used by the Portable Grid to open
	#Range: > 0
	openUsage = 1500
	#The energy used by the Portable Grid to extract items or fluids
	#Range: > 0
	extractUsage = 100
	#The energy used by the Portable Grid to insert items or fluids
	#Range: > 0
	insertUsage = 100

[crafter]
	#The energy used by the Crafter
	#Range: > 0
	usage = 64
	#The energy used for every Pattern in the Crafter
	#Range: > 0
	patternUsage = 16

[crafterManager]
	#The energy used by the Crafter Manager
	#Range: > 0
	usage = 16

[craftingMonitor]
	#The energy used by the Crafting Monitor
	#Range: > 0
	usage = 16

[wirelessCraftingMonitor]
	#The energy capacity of the Wireless Crafting Monitor
	#Range: > 0
	capacity = 640000
	#The energy used by the Wireless Crafting Monitor to open
	#Range: > 0
	openUsage = 1500
	#The energy used by the Wireless Crafting Monitor to cancel a crafting task
	#Range: > 0
	cancelUsage = 64
	#The energy used by the Wireless Crafting Monitor to cancel all crafting tasks
	#Range: > 0
	cancelAllUsage = 128